name: composer update
on:
  schedule:
    - '0 1 * * 1' # Every Monday 10:00(JST)
jobs:
  composer-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: none
      - name: composer update
        id: composer-update
        run: composer update
      - name: Create Pull Request
        if: steps.composer-update.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --exit-code; then
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="composer-update/$(date +'%Y%m%d')"
          git checkout -b ${BRANCH_NAME}
          git commit -am "composer update $(date +'%Y%m%d')"
          git push origin ${BRANCH_NAME}
          gh pr create -B "develop" -t "composer update" -b ""
