name: format
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
        default: ubuntu-latest
      php-version:
        required: true
        type: string
        default: '8.0'

jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: phpcbf
      - name: Format
        id: phpcbf
        continue-on-error: true
        run: phpcbf
      - name: Commit
        if: ${{ steps.phpcbf.outcome == 'failure' }}
        run: |
          git diff --exit-code
          if [[ $? == 0 ]]; then
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Apply PSR12"
          git push
