name: CI
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.**'
      - 'php**.xml'
      - '.github/workflows/**.yml'
      - '!.github/workflows/composer-update.yml'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      runs-on: ubuntu-20.04
      php-version: '8.1'
  format:
    needs: lint
    if: ${{ failure() }}
    uses: ./.github/workflows/format.yml
    with:
      runs-on: ubuntu-20.04
      php-version: '8.1'
  test:
    needs: lint
    if: ${{ success() }}
    uses: ./.github/workflows/test.yml
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    with:
      runs-on: ubuntu-20.04
      php-version: ${{ matrix.php-versions }}
