name: phpcs
on: ["push"]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs
      - name: Debug
        uses: mxschmitt/action-tmate@v3
      - name: Lint
        run: phpcs
